# minimal sensible defaults for local dev purposes
# https://besu.hyperledger.org/stable/public-networks/reference/cli/options

# network
bootnodes = [
  "enode://22631662a5c294a48ee177d9d3134da3ce0c0aa577aa120ca073ba6e1b07e1885976c54b164a947adacc88e27bd67228c83753e58ef5cb3395c1e477f9c8a7d3@validator-1:30303",
  "enode://7477d1eb2a4accd05b1c7db38cf3054d4a8cdf4efc5eff7d8a282ac9abaac06dd4266362b58c4c10cab0daebcbdd493023f03fb719f80039e72a4617cd57c6ae@validator-2:30303",
  "enode://2ffd1612758ab5d93a66ad72fd35a043f180d977c1201213f715502a686c670fbbd8587f5455530035c52b824262ee44f981709e7292413728a81af3794aae19@validator-3:30303",
  "enode://2e95e5b1c71df511efd214212c0d39bac9fb1dde388582aac786a77f1462b7b8b30c9f75f1d7eebeae436173de1b72789f9dd94f0da3a5581b9cd34563d7fdc8@validator-4:30303",
]
Xdns-enabled = true
Xdns-update-enabled = true

# node
genesis-file = "/opt/besu/genesis.json"
data-path = "/opt/besu/database"        # default of besu docker image
node-private-key-file = "/opt/besu/key" # default of besu docker image
host-allowlist = ["*"]
logging = "INFO"

# rpc http
rpc-http-enabled = true
rpc-http-host = "127.0.0.1" # default
rpc-http-port = 8545 # default
rpc-http-api = [
  "ETH",
  "NET",
  "WEB3",
  "ADMIN",
  "CLIQUE",
  "DEBUG",
  "EEA",
  "IBFT",
  "MINER",
  "PERM",
  "PLUGINS",
  "PRIV",
  "QBFT",
  "TRACE",
  "TXPOOL",
]
rpc-http-cors-origins = ["*"]

# rpc ws
rpc-ws-enabled = true
rpc-ws-host = "127.0.0.1" # default
rpc-ws-port = 8546 # default
rpc-ws-api = [
  "ETH",
  "NET",
  "WEB3",
  "ADMIN",
  "CLIQUE",
  "DEBUG",
  "EEA",
  "IBFT",
  "MINER",
  "PERM",
  "PLUGINS",
  "PRIV",
  "QBFT",
  "TRACE",
  "TXPOOL",
]

# graphql
graphql-http-enabled = true
graphql-http-host = "127.0.0.1"   # default
graphql-http-port = 8547          # default
graphql-http-cors-origins = ["*"]

# metrics
metrics-enabled = true
# metrics-host = "127.0.0.1"
metrics-host = "0.0.0.0"
metrics-port = 9545
# metrics-protocol = "PROMETHEUS"
metrics-category = [
  # default
  "BLOCKCHAIN",
  "ETHEREUM",
  "EXECUTORS",
  "JVM",
  "NETWORK",
  "PEERS",
  "PERMISSIONING",
  "PROCESS",
  "PRUNER",
  "RPC",
  "STRATUM",
  "SYNCHRONIZER",
  "TRANSACTION_POOL",
  # others
  "KVSTORE_ROCKSDB",
  "KVSTORE_PRIVATE_ROCKSDB",
  "KVSTORE_ROCKSDB_STATS",
  "KVSTORE_PRIVATE_ROCKSDB_STATS",
  # when private tx enabled
  # "PRIVATE",
]

# metrics-push (cannot be simultaneously used with metrics)
metrics-push-enabled = false
# metrics-push-host = "127.0.0.1"             # host of prometheus push gateway
# metrics-push-port = 9001                    # port of prometheus push gateway
# metrics-push-interval = 15                  # interval in seconds
# metrics-push-prometheus-job = "besu-client"
