services:
  validator-1:
    image: hyperledger/besu:23.4.0
    ports:
      - "30303"
      - "30303/udp"
      - "8545" # rpc-http
      - "8546" # rpc-ws
      - "8547" # graphql
    configs:
      - source: genesis.json
        target: /opt/besu/genesis.json
      - source: config.toml
        target: /opt/besu/config.toml
    secrets:
      - source: validator-1-private-key
        target: /opt/besu/key
    command: ["--config-file=/opt/besu/config.toml"]
  validator-2:
    image: hyperledger/besu:23.4.0
    ports:
      - "30303"
      - "30303/udp"
      - "8545" # rpc-http
      - "8546" # rpc-ws
      - "8547" # graphql
    configs:
      - source: genesis.json
        target: /opt/besu/genesis.json
      - source: config.toml
        target: /opt/besu/config.toml
    secrets:
      - source: validator-2-private-key
        target: /opt/besu/key
    command: ["--config-file=/opt/besu/config.toml"]
  validator-3:
    image: hyperledger/besu:23.4.0
    ports:
      - "30303"
      - "30303/udp"
      - "8545" # rpc-http
      - "8546" # rpc-ws
      - "8547" # graphql
    configs:
      - source: genesis.json
        target: /opt/besu/genesis.json
      - source: config.toml
        target: /opt/besu/config.toml
    secrets:
      - source: validator-3-private-key
        target: /opt/besu/key
    command: ["--config-file=/opt/besu/config.toml"]
  validator-4:
    image: hyperledger/besu:23.4.0
    ports:
      - "30303"
      - "30303/udp"
      - "8545" # rpc-http
      - "8546" # rpc-ws
      - "8547" # graphql
    configs:
      - source: genesis.json
        target: /opt/besu/genesis.json
      - source: config.toml
        target: /opt/besu/config.toml
    secrets:
      - source: validator-4-private-key
        target: /opt/besu/key
    command: ["--config-file=/opt/besu/config.toml"]

configs:
  genesis.json:
    file: ./genesis.json
  config.toml:
    file: ./config.toml

secrets:
  validator-1-private-key:
    file: ./validator-1/key.priv
  validator-2-private-key:
    file: ./validator-2/key.priv
  validator-3-private-key:
    file: ./validator-3/key.priv
  validator-4-private-key:
    file: ./validator-4/key.priv
