services:
  validator-1:
    image: hyperledger/besu:${TAG:-23.10.0}
    ports:
      - "30303"
      - "30303/udp"
      - "127.0.0.1:8545:8545" # rpc-http
      - "127.0.0.1:8546:8546" # rpc-ws
      - "127.0.0.1:8547:8547" # graphql
      - "127.0.0.1:8551:8551" # engine-rpc
      - "127.0.0.1:9545:9545" # metrics
    configs:
      - source: genesis.json
        target: /opt/besu/genesis.json
      - source: config.toml
        target: /opt/besu/config.toml
    secrets:
      - source: validator-1-private-key
        target: /opt/besu/key
    command: [
        "--config-file=/opt/besu/config.toml",
        # "--rpc-http-host=0.0.0.0", # bug: config.toml value is ignored
        # "--rpc-ws-host=0.0.0.0", # bug: config.toml value is ignored
        # "--graphql-http-host=0.0.0.0", # bug: config.toml value is ignored
      ]
  validator-2:
    image: hyperledger/besu:${TAG:-23.10.0}
    ports:
      - "30303"
      - "30303/udp"
      - "8545" # rpc-http
      - "8546" # rpc-ws
      - "8547" # graphql
      - "8551" # engine-rpc
      - "9545" # metrics
    configs:
      - source: genesis.json
        target: /opt/besu/genesis.json
      - source: config.toml
        target: /opt/besu/config.toml
    secrets:
      - source: validator-2-private-key
        target: /opt/besu/key
    command: [
        "--config-file=/opt/besu/config.toml",
        # "--rpc-http-host=0.0.0.0", # bug: config.toml value is ignored
        # "--rpc-ws-host=0.0.0.0", # bug: config.toml value is ignored
        # "--graphql-http-host=0.0.0.0", # bug: config.toml value is ignored
      ]
  validator-3:
    image: hyperledger/besu:${TAG:-23.10.0}
    ports:
      - "30303"
      - "30303/udp"
      - "8545" # rpc-http
      - "8546" # rpc-ws
      - "8547" # graphql
      - "8551" # engine-rpc
      - "9545" # metrics
    configs:
      - source: genesis.json
        target: /opt/besu/genesis.json
      - source: config.toml
        target: /opt/besu/config.toml
    secrets:
      - source: validator-3-private-key
        target: /opt/besu/key
    command: [
        "--config-file=/opt/besu/config.toml",
        # "--rpc-http-host=0.0.0.0", # bug: config.toml value is ignored
        # "--rpc-ws-host=0.0.0.0", # bug: config.toml value is ignored
        # "--graphql-http-host=0.0.0.0", # bug: config.toml value is ignored
      ]
  validator-4:
    image: hyperledger/besu:${TAG:-23.10.0}
    ports:
      - "30303"
      - "30303/udp"
      - "8545" # rpc-http
      - "8546" # rpc-ws
      - "8547" # graphql
      - "8551" # engine-rpc
      - "9545" # metrics
    configs:
      - source: genesis.json
        target: /opt/besu/genesis.json
      - source: config.toml
        target: /opt/besu/config.toml
    secrets:
      - source: validator-4-private-key
        target: /opt/besu/key
    command: [
        "--config-file=/opt/besu/config.toml",
        # "--rpc-http-host=0.0.0.0", # bug: config.toml value is ignored
        # "--rpc-ws-host=0.0.0.0", # bug: config.toml value is ignored
        # "--graphql-http-host=0.0.0.0", # bug: config.toml value is ignored
      ]

configs:
  genesis.json:
    file: ./genesis.json
  config.toml:
    file: ./config.toml

secrets:
  validator-1-private-key:
    file: ./validator-1/key.priv
  validator-2-private-key:
    file: ./validator-2/key.priv
  validator-3-private-key:
    file: ./validator-3/key.priv
  validator-4-private-key:
    file: ./validator-4/key.priv
